food/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("result/", views.result, name="result"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("food.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models

# Create your models here.

class UploadedPhoto(models.Model):
    photo = models.ImageField(upload_to='photos/')

food/forms.py
from django import forms
from .models import *

class UploadPhotoForm(forms.ModelForm):
    class Meta:
        model = UploadedPhoto
        fields = ['photo']

food/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from web_project.settings import MEDIA_ROOT
from .forms import *
from .models import *

import os

# Create your views here.
def home(request):
    # Delete photos
    photosdir = os.path.join(MEDIA_ROOT, 'photos')
    for dir in os.listdir(photosdir):
        os.remove(os.path.join(photosdir, dir))
    # Delete photo objects
    UploadedPhoto.objects.all().delete()

    if request.method == 'POST':
        form = UploadPhotoForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            photo = UploadedPhoto.objects.last()
            request.session['url'] = photo.photo.url
            return redirect('result')
        # TODO: Print an error if form is not valid.
        # TODO: Make the photo have a size requirement.
        # TODO: Turn the photo B&W / resize if necessary for processing.
    else:
        form = UploadPhotoForm()
    return render(request, 'home.html', {'form' : form})

def result(request):
    context = {}
    if('url' in request.session):
        context['url'] = request.session['url']
        del request.session['url']

    return render(request, 'result.html', context)

food/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/794d917592.js" crossorigin="anonymous"></script>

    <title>{% block title %}FoodFacts{% endblock %}</title>

    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="static/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="static/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="static/images/favicon-16x16.png">
    <link rel="manifest" href="static/images/site.webmanifest">
    <link rel="mask-icon" href="static/images/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="theme-color" content="#f3bd0f">
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <p class="text-center display-1 p-1">Food <i class="fa-solid fa-utensils"></i> Facts</p>

    {% block content %}
    {% endblock %}
    
    <footer class="bg-warning text-center text-lg-start">
        <div class="container p-2">
          <div class="row justify-content-md-center">
            <div class="col-md-auto">
              <a class="text-light text-center" style="text-decoration:none" href="{% url 'home' %}"><h5>FoodFacts</h5></a>
            </div>
          </div>
          <div class="row">
            <div class="col-sm">
              <section class="text-center">
                <a
                  class="btn btn-link btn-floating btn-lg text-light m-1"
                  href="https://github.com/melend53/FoodFacts/"
                  role="button"
                  ><i class="fab fa-github"></i
                ></a>
                <a
                  class="btn btn-link btn-floating btn-lg text-light m-1"
                  href="https://devpost.com/software/foodfacts-6sz92n"
                  role="button"
                  ><i class="fa-solid fa-d"></i
                ></a>
              </section>
              <p class="text-light text-center">Created by Devyn Melendez & Lucas Grebe for ProfHacks 2022</p>
            </div>
          </div>
        </div>
    </footer>
  </body>

</html>

food/templates/food/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/794d917592.js" crossorigin="anonymous"></script>

    <title>{% block title %}FoodFacts{% endblock %}</title>

    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="theme-color" content="#f3bd0f">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}
    <footer class="bg-warning text-center text-lg-start">
        <div class="container p-2">
          <div class="row justify-content-md-center">
            <div class="col-md-auto">
              <a class="text-light text-center" style="text-decoration:none" href="{% url 'food' %}"><h5>FoodFacts</h5></a>
            </div>
          </div>
          <div class="row">
            <div class="col-sm">
              <section class="text-center">
                <a
                  class="btn btn-link btn-floating btn-lg text-light m-1"
                  href="https://github.com/melend53/FoodFacts/"
                  role="button"
                  ><i class="fab fa-github"></i
                ></a>
                <a
                  class="btn btn-link btn-floating btn-lg text-light m-1"
                  href="https://devpost.com/software/foodfacts-6sz92n"
                  role="button"
                  ><i class="fa-solid fa-d"></i
                ></a>
              </section>
              <p class="text-light text-center">Created by Devyn Melendez & Lucas Grebe for ProfHacks 2022</p>
            </div>
          </div>
        </div>
    </footer>
  </body>
</html>

food/templates/food/food.html
{% extends 'base.html' %}

{% block content %}
<p class="text-center display-1 p-1">Food <i class="fa-solid fa-utensils"></i> Facts</p>
    
<div class="container p-4">
  <div class="row">
    <div class="col-sm text-center">
      <p>FoodFacts uses a trained neural network to recognize snapshots of your food, and display its nutritional value.</p>
      <p><b>Upload a snapshot below to get its nutritional data!</b> <i class="fa-solid fa-camera"></i></p>
      <form enctype="multipart/form-data" action="" method="post">
        <input type="file" class="form-control form-control-lg" id="formFile" accept="image/*"><br>
        <input class="btn btn-danger btn-lg" type="submit" value="Upload">
      </form>
    </div>
  </div>
</div>
{% endblock %}

food/templates/home.html
{% extends 'base.html' %}

{% block content %}    
<div class="container p-4">
  <div class="row">
    <div class="col-sm text-center">
      <p>FoodFacts uses a trained neural network to recognize snapshots of your food, and display its nutritional value.</p>
      <p><b>Upload a snapshot below to get its nutritional data!</b> <i class="fa-solid fa-camera"></i></p>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <input type="file" class="form-control form-control-lg" name="{{ form.photo.name }}" required id="id_photo" accept="image/*">
        <br>
        <input class="btn btn-danger btn-lg" type="submit" value="Upload">
      </form>
    </div>
  </div>
</div>
{% endblock %}

food/templates/result.html
{% extends 'base.html' %}

{% block title %}FoodFacts | Result{% endblock %}

{%block content %}
{% if url %}
<div class="container p-4">
    <div class="row">
      <div class="col-sm text-center">
        <p>Your photo was processed successfully.</p>
      </div>
    </div>
    <div class="row p-4">
      <div class="col-sm text-center">
        <img src="{{ url }}" class="img-responsive"/>
      </div>
    </div>
    <div class="row">
        <div class="col-sm text-center">
            <a class="btn btn-danger btn-lg" href="{% url 'home' %}" role="button">Back to homepage</a>
        </div>
    </div>
  </div>
{% else %}
<div class="container p-4">
    <div class="row">
        <div class="col-sm text-center">
            <p>This page is supposed to contain your nutrition facts.</p>
            <p>Are you sure you uploaded a photo?</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm text-center">
            <a class="btn btn-danger btn-lg" href="{% url 'home' %}" role="button">Back to homepage</a>
        </div>
    </div>
</div>
{% endif %}
<!-- <img src="{{ url }}" class="img-responsive"/> -->
{% endblock %}